# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project-4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CalendarKit'
  pod 'CVCalendar', '~> 1.6.2'

end
